  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module constantinople::choice {

  public enum Choice has copy, drop , store {
                                Paper,Rock,Scissors
                        }

  public fun new_paper(): Choice {
    Choice::Paper
  }

  public fun new_rock(): Choice {
    Choice::Rock
  }

  public fun new_scissors(): Choice {
    Choice::Scissors
  }
}
