  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module constantinople::map_config {

  use std::ascii::String;

  public struct MapConfig has copy, drop, store {
    width: u64,
    height: u64,
    terrain: vector<vector<u8>>,
  }

  public fun new(width: u64, height: u64, terrain: vector<vector<u8>>): MapConfig {
    MapConfig {
                                   width,height,terrain
                               }
  }

  public fun get(self: &MapConfig): (u64,u64,vector<vector<u8>>) {
    (self.width,self.height,self.terrain)
  }

  public fun get_width(self: &MapConfig): u64 {
    self.width
  }

  public fun get_height(self: &MapConfig): u64 {
    self.height
  }

  public fun get_terrain(self: &MapConfig): vector<vector<u8>> {
    self.terrain
  }

  public(package) fun set_width(self: &mut MapConfig, width: u64) {
    self.width = width;
  }

  public(package) fun set_height(self: &mut MapConfig, height: u64) {
    self.height = height;
  }

  public(package) fun set_terrain(self: &mut MapConfig, terrain: vector<vector<u8>>) {
    self.terrain = terrain;
  }

  public(package) fun set(self: &mut MapConfig, width: u64, height: u64, terrain: vector<vector<u8>>) {
    self.width = width;
    self.height = height;
    self.terrain = terrain;
  }
}
