  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module constantinople::map_config {

  use std::ascii::String;

  use constantinople::monster_type::MonsterType;

  use constantinople::direction::Direction;

  use constantinople::terrain_type::TerrainType;

  use constantinople::monster_catch_result::MonsterCatchResult;

  public struct MapConfig has copy, drop, store {
    width: u64,
    height: u64,
    terrain: vector<vector<TerrainType>>,
  }

  public fun new(width: u64, height: u64, terrain: vector<vector<TerrainType>>): MapConfig {
    MapConfig {
                                   width,height,terrain
                               }
  }

  public fun get(self: &MapConfig): (u64,u64,vector<vector<TerrainType>>) {
    (self.width,self.height,self.terrain)
  }

  public fun get_width(self: &MapConfig): u64 {
    self.width
  }

  public fun get_height(self: &MapConfig): u64 {
    self.height
  }

  public fun get_terrain(self: &MapConfig): vector<vector<TerrainType>> {
    self.terrain
  }

  public(package) fun set_width(self: &mut MapConfig, width: u64) {
    self.width = width;
  }

  public(package) fun set_height(self: &mut MapConfig, height: u64) {
    self.height = height;
  }

  public(package) fun set_terrain(self: &mut MapConfig, terrain: vector<vector<TerrainType>>) {
    self.terrain = terrain;
  }

  public(package) fun set(self: &mut MapConfig, width: u64, height: u64, terrain: vector<vector<TerrainType>>) {
    self.width = width;
    self.height = height;
    self.terrain = terrain;
  }
}
