  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module constantinople::cannot_move_error {

  #[error]

  const CannotMove: vector<u8> = b"This entity cannot move";

  /// Get the error message.

  public fun message(): vector<u8> {
    CannotMove
  }

  /// Abort execution with the given error code.

  public fun emit() {
    abort CannotMove
  }

  /// Require that the given condition is true, otherwise abort with the given error code.

  public fun require(condition: bool) {
    if (!condition) { emit() }
  }
}
