  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module constantinople::not_in_encounter_error {

  #[error]

  const NotInEncounter: vector<u8> = b"This player is not in an encounter";

  /// Get the error message.

  public fun message(): vector<u8> {
    NotInEncounter
  }

  /// Abort execution with the given error code.

  public fun emit() {
    abort NotInEncounter
  }

  /// Require that the given condition is true, otherwise abort with the given error code.

  public fun require(condition: bool) {
    if (!condition) { emit() }
  }
}
