  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module constantinople::space_obstructed_error {

  #[error]

  const SpaceObstructed: vector<u8> = b"This space is obstructed";

  /// Get the error message.

  public fun message(): vector<u8> {
    SpaceObstructed
  }

  /// Abort execution with the given error code.

  public fun emit() {
    abort SpaceObstructed
  }

  /// Require that the given condition is true, otherwise abort with the given error code.

  public fun require(condition: bool) {
    if (!condition) { emit() }
  }
}
