export * as groundImg1 from "./50.png";
export * as groundImg2 from "./51.png";
export * as groundImg3 from "./52.png";
export * as groundImg4 from "./53.png";
export * as groundImg5 from "./54.png";
export * as groundImg6 from "./55.png";
export * as groundImg7 from "./56.png";
export * as groundImg8 from "./57.png";
export * as groundImg9 from "./58.png";